name: .NET CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release

    # 🔥 Trigger Jenkins After Success
    - name: Trigger Jenkins Pipeline
      if: success()
      run: |
        curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB }}/build?token=${{ secrets.JENKINS_TRIGGER_TOKEN }}"
